version: '3'
services:
  tile38:
    image: tile38/tile38
    container_name: tile38
    ports:
        - 9851:9851
    restart: unless-stopped

  tile38-viewer:
    image: leighghunt/tile38-viewer
    container_name: tile38-viewer
    build: ./src/viewer
    environment:
      - Tile38Connection=${ConnectionStrings:Tile38Connection}
      - HubConnection=${ConnectionStrings:HubConnection}
      - ScanForNewGeoFences_ms=${ScanForNewGeoFences_ms}
      - ScanForNewKeys_ms=${ScanForNewKeys_ms}
      - RefreshInterval=${RefreshInterval}
      - UseWebSocketsForMovementUpdates=${UseWebSocketsForMovementUpdates}
    env_file: ./docker-environment-list.env
    depends_on:
        - tile38
    ports:
      - 5000:80
      - 5001:443
    restart: unless-stopped

  tile38-worker:
    image: leighghunt/tile38-worker
    container_name: tile38-worker
    build: ./src/worker
    environment:
      - Tile38Connection=${ConnectionStrings:Tile38Connection}
      - HubConnection=${ConnectionStrings:HubConnection}
      - ScanForNewGeoFences_ms=${ScanForNewGeoFences_ms}
      - ScanForNewKeys_ms=${ScanForNewKeys_ms}
      - RefreshInterval=${RefreshInterval}
      - UseWebSocketsForMovementUpdates=${UseWebSocketsForMovementUpdates}
    env_file: ./docker-environment-list.env
    depends_on:
        - tile38
        - tile38-viewer
    restart: unless-stopped
